version: '3.8'

services:
  postgres-test:
    image: 'postgres:10.7'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 54329:5432

  selenium-test:
    image: 'selenium/standalone-chrome'
    ports:
      - 44441:4444

